<?php


namespace App\Tests\Features;


use App\Entity\Comment;
use App\Entity\Like;
use App\Entity\Post;
use App\Entity\User;
use Liip\TestFixturesBundle\Services\DatabaseToolCollection;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class FeaturesTestsSetup extends WebTestCase
{
    /**
     * @var \Symfony\Bundle\FrameworkBundle\KernelBrowser
     */
    protected $client;
    protected $doctrine;
    protected $databaseTools;
    protected $commentRepository;
    protected $postRepository;
    protected $userRepository;
    protected $user;
    protected $likeRepository;



    protected function setUp(): void
    {
        self::ensureKernelShutdown();

        $this->client = static::createClient();

        $this->doctrine = static::getContainer()->get('doctrine')->getManager();


        $this->databaseTools = static::getContainer()->get(DatabaseToolCollection::class)->get();
        $this->databaseTools->loadAliceFixture([__DIR__."\UserFixtures.yaml"]);

        $this->postRepository = $this->doctrine->getRepository(Post::class);
        $this->likeRepository = $this->doctrine->getRepository(Like::class);
        $this->userRepository = $this->doctrine->getRepository(User::class);
        $this->commentRepository = $this->doctrine->getRepository(Comment::class);


        parent::setUp(); // TODO: Change the autogenerated stub
    }

}