<?php


namespace App\Tests\Entities;


use App\Entity\Like;
use App\Entity\Post;
use App\Entity\User;
use Liip\TestFixturesBundle\Services\DatabaseToolCollection;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class LikesTest extends WebTestCase
{

    private $doctrine;
    private $databaseTool;
    private $postRepository;
    private $userRepository;
    private $likeRepository;

    protected function setUp(): void
    {
        static::bootKernel();
        $this->doctrine = static::getContainer()->get('doctrine')->getManager();
        $this->databaseTool = static::getContainer()->get(DatabaseToolCollection::class)->get();

        $this->databaseTool->loadAliceFixture([__DIR__."/UserFixtures.yaml"]);
        $this->postRepository = $this->doctrine->getRepository(Post::class);
        $this->userRepository = $this->doctrine->getRepository(User::class);
        $this->likeRepository = $this->doctrine->getRepository(Like::class);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     * @group unitTest
     */
    public function test_like_is_counted(){

        // Find a User and a  Post to create a like
        $post = $this->postRepository->find(1);
        $user = $this->userRepository->find(1);


        $like = new like();
        $like->setUser($user);
        $like->setPost($post);


        $this->doctrine->persist($like);
        $this->doctrine->flush();

        //Check if like is in DB
        $dbLike = $this->likeRepository->find(1);

        $this->assertEquals($user, $like->getUser());
        $this->assertEquals($post, $like->getPost());

    }

}