<?php


namespace App\Tests\Features\Ajax;


use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\JsonResponse;

class AjaxFeatureTest extends WebTestCase
{
    // Test if Json return

    /**
     * @var \Symfony\Bundle\FrameworkBundle\KernelBrowser
     */
    private $client;

    protected function setUp(): void
    {
        $this->client = static::createClient();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     *@test
     * @group ajaxTest
     */
    public function test_json_response_to_like_function(){


        $post = $this->client->request("GET", "post/like/1");
    }

}